name: gh1

on:
  push:
    branches: [ nodejs_nodeversions_job ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12]

    steps:
    - name: Obtencion del codigo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node }}
    - uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: nodejs_linter_job
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
        VALIDATE_JAVASCRIPT_ES: true
